Add files via upload
anq420/domashka.com pull request #1
Opened 2023-12-02 18:10 UTC by anq420

2023-12-03 10:00 UTC, nicilytop requested changes
correct you check

2023-12-03 10:00 UTC, nicilytop commented on lesson_12_hm.py
> +        elif self.status is not None:
lets connect with Bogdan.. the same error

2023-12-03 10:00 UTC, nicilytop commented on lesson_12_hm.py
> +        elif self.status is not None:
we dont need this check.. if my car was muted and I will want mute it - I do it again - it is amazing

2023-12-04 10:23 UTC, nicilytop-tms approved these changes
good job 😎

2023-12-05 05:50 UTC, closed without merging