Add files via upload
anq420/domashka.com pull request #10
Opened 2023-12-27 22:20 UTC by anq420

![image](https://github.com/anq420/domashka.com/assets/149022595/c2a4ccac-a20b-4bf1-8aee-a5cbc9a9c77b)

2023-12-28 05:54 UTC, nicilytop-tms requested changes
Hash your password please

2023-12-28 05:54 UTC, nicilytop-tms commented on lesson_19_hw/lesson_19_hw.py
> +users = Table(
Better to separate it on different modules

2023-12-28 05:54 UTC, nicilytop-tms commented on lesson_19_hw/lesson_19_hw.py
> +metadata = MetaData()
does it work?

2023-12-28 05:54 UTC, nicilytop-tms commented on lesson_19_hw/lesson_19_hw.py
> +                new_account = users.insert().values(email=email, password=password, nickname=nickname)
we should hash password

2023-12-28 12:24 UTC, anq420 commented on lesson_19_hw/lesson_19_hw.py
> +metadata = MetaData()
What do you mean?

2024-01-08 07:40 UTC, nicilytop-tms approved these changes

2024-01-10 23:14 UTC, merged